version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery_worker:
    build: .
    command: python worker.py
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "5000:8000"
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
    restart: unless-stopped

volumes:
  redis_data:
