version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --protected-mode no --save "" --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru --dir /tmp --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network

  celery_worker:
    build: .
    command: python worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "3006:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis_data:


networks:
  app-network:
    driver: bridge
