version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    command: redis-server --bind 0.0.0.0 --protected-mode no
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "5000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:


networks:
  app-network:
    driver: bridge
